name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

     runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - uses: azure/docker-login@v1
      with:
        login-server: newregistery2.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME1 }}
        password: ${{ secrets.REGISTRY_PASSWORD1 }}
    
    - run: |
        docker build . -t newregistery2.azurecr.io/pythonc:${{ github.sha }}
        docker push newregistery2.azurecr.io/pythonc:${{ github.sha }}
